/* Tests v2 skips by name until it draws their chart family.
 *
 * CHART_ENGINE=v2 runs every test in tests/js against v2; the ones listed
 * here are skipped, keyed "<test file>: <test name>" (the drawing snapshots
 * are all registered by run-case.js). Each build step removes its family's
 * entries. A test of a built family must match v1 or have its difference
 * listed in v2-differences.json.
 *
 * V2_RUN_PENDING=1 runs them anyway, to see which already pass.
 */
'use strict';

module.exports = {
  // Step 2b: bar, waterfall, pie, treemap, radar, boxplot, pointrange, and the
  // lifecycle, message and export tests drawn with a bar.
  aggregated: [
    'busy-cue.test.js: a slow draw shows the cue, and the drawn picture ends it',
    'busy-cue.test.js: a message without rows keeps the cue until the rows arrive',
    'busy-cue.test.js: R ends the cue when no picture is coming',
    'run-case.js: bar-defaults',
    'run-case.js: bar-group',
    'run-case.js: bar-color-stacked',
    'run-case.js: bar-color-grouped',
    'run-case.js: bar-color-percent',
    'run-case.js: bar-vertical',
    'run-case.js: bar-vertical-narrow',
    'run-case.js: bar-vertical-grouped',
    'run-case.js: bar-mean',
    'run-case.js: bar-facet-fixed',
    'run-case.js: bar-facet-free',
    'run-case.js: bar-facet-cols',
    'run-case.js: bar-count-axis',
    'run-case.js: bar-count-axis-distinct',
    'run-case.js: bar-count-both-facet',
    'run-case.js: bar-sort-value-asc',
    'run-case.js: bar-sort-alpha-desc',
    'run-case.js: bar-sort-data',
    'run-case.js: bar-sort-alpha-factor',
    'run-case.js: bar-sort-column',
    'run-case.js: bar-value-labels',
    'run-case.js: bar-value-labels-vertical-grouped',
    'run-case.js: bar-value-labels-percent',
    'run-case.js: bar-pct-distinct-facet',
    'run-case.js: bar-pct-distinct-color',
    'run-case.js: bar-na-group-drop',
    'run-case.js: bar-tt-fields',
    'run-case.js: bar-drill-off',
    'run-case.js: bar-selected',
    'run-case.js: bar-identity-count-col',
    'run-case.js: bar-value-lines',
    'run-case.js: bar-scales',
    'run-case.js: bar-palette-overflow',
    'run-case.js: bar-too-many-colors',
    'run-case.js: bar-missing-column',
    'run-case.js: bar-titles',
    'run-case.js: bar-theme-dark',
    'run-case.js: bar-resend',
    'run-case.js: waterfall',
    'run-case.js: waterfall-totals-labels',
    'run-case.js: pie',
    'run-case.js: pie-facet-selected',
    'run-case.js: treemap',
    'run-case.js: radar',
    'run-case.js: radar-nocolor',
    'run-case.js: radar-facet',
    'run-case.js: boxplot',
    'run-case.js: boxplot-color-outliers',
    'run-case.js: boxplot-horizontal-count',
    'run-case.js: boxplot-facet-color',
    'run-case.js: boxplot-stats',
    'run-case.js: boxplot-no-value',
    'run-case.js: pointrange',
    'run-case.js: pointrange-color-connect',
    'chart-payload.test.js: bar-color-stacked: dictionary-encoded columns draw the same',
    'chart-payload.test.js: bar-color-stacked: a JSON string payload draws the same',
    'chart-payload.test.js: boxplot-color-outliers: dictionary-encoded columns draw the same',
    'chart-payload.test.js: boxplot-color-outliers: a JSON string payload draws the same',
    'chart-push.test.js: a message without rows reuses the rows and draws the new config',
    'chart-push.test.js: a message without rows draws what the same message with rows draws',
    'chart-push.test.js: a message without rows merges into a payload waiting for its container',
    'chart-push.test.js: a client without the rows asks for them once, and draws nothing until they come',
    'chart-push.test.js: a container that binds to a message without rows asks for them',
    'chart-push.test.js: the reply to _ready does not redraw a client that got the push',
    'chart-push.test.js: the reply to _ready makes a client without the rows ask for them',
    'interactions-click.test.js: bar-latched',
    'interactions-click.test.js: bar-color',
    'interactions-click.test.js: bar-grouped-vertical',
    'interactions-click.test.js: bar-facet-drill-column',
    'interactions-click.test.js: bar-drill-off',
    'interactions-click.test.js: bar-transient',
    'interactions-click.test.js: bar-transient-drill-off',
    'interactions-click.test.js: bar-transient-drill-column',
    'interactions-click.test.js: waterfall',
    'interactions-click.test.js: pie',
    'interactions-click.test.js: pie-facet',
    'interactions-click.test.js: pie-transient',
    'interactions-click.test.js: treemap',
    'interactions-click.test.js: radar-color',
    'interactions-click.test.js: radar-nocolor',
    'interactions-click.test.js: radar-drill-column',
    'interactions-click.test.js: radar-facet',
    'interactions-click.test.js: boxplot',
    'interactions-click.test.js: boxplot-color',
    'interactions-click.test.js: boxplot-facet',
    'interactions-click.test.js: pointrange',
    'interactions-click.test.js: pointrange-color',
    'interactions-click.test.js: legend-bar-facet',
    'interactions-export.test.js: compose: titles, one panel, caption, the done callback',
    'interactions-export.test.js: compose: facet panels and the legend band, default ratio',
    'interactions-export.test.js: compose: capture_ratio from the config, sent to R as <id>_capture',
    'interactions-export.test.js: compose: no callback and no send saves chart.png in the browser',
    'interactions-export.test.js: compose: nothing to compose',
    'interactions-export.test.js: drilldown-capture: a picture, one reply, the host removed',
    'interactions-export.test.js: drilldown-capture: a chart that cannot draw answers after 20 s',
    'interactions-export.test.js: drilldown-capture: a payload that throws answers at once',
    'interactions-export.test.js: drilldown-capture: two requests in flight',
    'interactions-gear.test.js: outline: bar',
    'interactions-gear.test.js: outline: bar-facet-counts',
    'interactions-gear.test.js: outline: bar-drill-off',
    'interactions-gear.test.js: outline: bar-drill-column-ctrl',
    'interactions-gear.test.js: outline: bar-ctrl-missing-target',
    'interactions-gear.test.js: outline: waterfall',
    'interactions-gear.test.js: outline: pie',
    'interactions-gear.test.js: outline: treemap',
    'interactions-gear.test.js: outline: radar',
    'interactions-gear.test.js: outline: boxplot',
    'interactions-gear.test.js: outline: pointrange',
    'interactions-gear.test.js: outline: bar-defaults',
    'interactions-gear.test.js: outline: Titles fold opened, Prepare script fold closed',
    'interactions-gear.test.js: outline: script controls on the band',
    'interactions-gear.test.js: drive: bar',
    'interactions-gear.test.js: drive: bar-mapping',
    'interactions-gear.test.js: drive: bar-drill',
    'interactions-gear.test.js: drive: bar-selection-then-mapping',
    'interactions-gear.test.js: drive: type-switch',
    'interactions-gear.test.js: drive: boxplot',
    'interactions-gear.test.js: drive: titles',
    'interactions-gear.test.js: drive: script-band',
    'interactions-gear.test.js: drive: await-data',
    'interactions-lifecycle.test.js: bind with nothing waiting: the card, and the _ready announce',
    'interactions-lifecycle.test.js: bind with a payload and a theme waiting: drawn, no announce',
    'interactions-lifecycle.test.js: dock re-mount: a new element under the same id',
    'interactions-lifecycle.test.js: initialize twice on one element',
    'interactions-lifecycle.test.js: dispose',
    'interactions-lifecycle.test.js: drilldown-theme: re-creates the instances with the theme',
    'interactions-lifecycle.test.js: drilldown-theme before any data: no draw',
    'interactions-lifecycle.test.js: data-bs-theme on <html> redraws every chart holding rows',
    'interactions-lifecycle.test.js: resize: the 300 ms pass, hidden and empty containers, the observer',
    'interactions-lifecycle.test.js: resize: a vertical bar re-fits its x labels to the new width',
    'interactions-lifecycle.test.js: facet grid at several widths and panel-column settings',
    'interactions-lifecycle.test.js: an empty container never throws on resize',
    'interactions-messages.test.js: data-with-rows',
    'interactions-messages.test.js: data-without-rows',
    'interactions-messages.test.js: ready',
    'interactions-messages.test.js: busy',
    'interactions-messages.test.js: busy-without-rows',
    'interactions-messages.test.js: data before the container exists',
    'interactions-restore.test.js: bar-single',
    'interactions-restore.test.js: bar-multi',
    'interactions-restore.test.js: bar-column-differs',
    'interactions-restore.test.js: bar-no-column',
    'interactions-restore.test.js: bar-transient',
    'interactions-restore.test.js: bar-echo-keeps',
    'interactions-restore.test.js: pie',
    'interactions-restore.test.js: treemap',
    'interactions-restore.test.js: radar',
    'interactions-restore.test.js: boxplot-color',
    'interactions-restore.test.js: waterfall',
    'interactions-restore.test.js: a transient receipt survives a re-render at its own age',
    'interactions-sentence.test.js: sentence words and offers',
    'scaling.test.js: scaling: bar, 200 terms by arm',
    'scaling.test.js: scaling: bar, faceted by arm',
    'scaling.test.js: scaling: pie',
    'scaling.test.js: scaling: boxplot by visit',
    'scaling.test.js: scaling: boxplot, group = patient, colour = arm',
    'scaling.test.js: scaling: boxplot, group = patient, colour = grade, faceted by arm',
    'scaling.test.js: scaling: bar, group = patient, colour = grade',
    'scaling.test.js: scaling: bar percent, group = patient, colour = grade',
    'scaling.test.js: scaling: radar, group = patient, colour = arm',
    'scaling.test.js: scaling: pie, group = patient',
    'scaling.test.js: scaling: treemap, group = patient',
    'scaling.test.js: scaling: waterfall, group = patient'
  ],
  // Step 2c: scatter, line, band.
  individual: [
    'interactions-click.test.js: legend-line-series-color-facet',
    'chart-brush.test.js: brush with a drill column: every row once in the drill payload',
    'chart-brush.test.js: brush without a drill column: a range over every brushed point',
    'run-case.js: scatter-defaults',
    'run-case.js: scatter',
    'run-case.js: scatter-color',
    'run-case.js: scatter-series',
    'run-case.js: scatter-series-color',
    'run-case.js: scatter-facet-fixed',
    'run-case.js: scatter-facet-free-y',
    'run-case.js: scatter-identity',
    'run-case.js: scatter-smoother',
    'run-case.js: scatter-smoother-color',
    'run-case.js: scatter-smoother-facet',
    'run-case.js: scatter-errorbars-refs',
    'run-case.js: scatter-tt-fields',
    'run-case.js: scatter-categorical-x',
    'run-case.js: scatter-drill-off',
    'run-case.js: line',
    'run-case.js: line-series-color',
    'run-case.js: line-categorical-x',
    'run-case.js: line-facet-counts',
    'run-case.js: line-single-step-errorbars',
    'run-case.js: line-color-only',
    'run-case.js: band',
    'run-case.js: band-color',
    'run-case.js: band-facet-refs',
    'run-case.js: band-note',
    'chart-payload.test.js: scatter-series-color: dictionary-encoded columns draw the same',
    'chart-payload.test.js: scatter-series-color: a JSON string payload draws the same',
    'chart-payload.test.js: line-facet-counts: dictionary-encoded columns draw the same',
    'chart-payload.test.js: line-facet-counts: a JSON string payload draws the same',
    'interactions-brush.test.js: scatter-geometric',
    'interactions-brush.test.js: scatter-ignored-events',
    'interactions-brush.test.js: scatter-color',
    'interactions-brush.test.js: scatter-facet',
    'interactions-brush.test.js: scatter-drill-column',
    'interactions-brush.test.js: scatter-drill-off',
    'interactions-brush.test.js: scatter-transient',
    'interactions-brush.test.js: scatter-click-guard',
    'interactions-brush.test.js: line-event',
    'interactions-brush.test.js: scatter-duplicate-points',
    'interactions-click.test.js: scatter-geometric',
    'interactions-click.test.js: scatter-color',
    'interactions-click.test.js: scatter-series',
    'interactions-click.test.js: scatter-facet-drill-column',
    'interactions-click.test.js: scatter-drill-off',
    'interactions-click.test.js: scatter-transient',
    'interactions-click.test.js: scatter-transient-geometric',
    'interactions-click.test.js: scatter-non-series',
    'interactions-click.test.js: line-series',
    'interactions-click.test.js: line-dblclick-cancels',
    'interactions-click.test.js: line-hover-wins',
    'interactions-click.test.js: line-color-only',
    'interactions-click.test.js: line-no-split',
    'interactions-click.test.js: line-transient',
    'interactions-click.test.js: band-color',
    'interactions-click.test.js: band-plain',
    'interactions-gear.test.js: outline: scatter',
    'interactions-gear.test.js: outline: scatter-facet',
    'interactions-gear.test.js: outline: line',
    'interactions-gear.test.js: outline: band',
    'interactions-gear.test.js: drive: scatter',
    'interactions-gear.test.js: drive: line',
    'interactions-gear.test.js: drive: band',
    'interactions-hover.test.js: line-series: picker grid',
    'interactions-hover.test.js: line-categorical-x: picker grid (x is the category index)',
    'interactions-hover.test.js: line-color-only: picker grid',
    'interactions-hover.test.js: single line, scatter and band: no line focus',
    'interactions-hover.test.js: line-series: mousemove promotes, moves, demotes',
    'interactions-hover.test.js: line-facet: each panel picks its own lines',
    'interactions-hover.test.js: band-color: level picker grid',
    'interactions-hover.test.js: band-color: mousemove reveals the nearest ribbon',
    'interactions-hover.test.js: band-facet: no colour split, no ribbon picker',
    'interactions-restore.test.js: scatter',
    'interactions-restore.test.js: line',
    'interactions-restore.test.js: line zoom window survives a re-render, a type switch forgets it',
    'interactions-restore.test.js: a brush filter survives a re-render',
    'scaling.test.js: scaling: scatter',
    'scaling.test.js: scaling: line, faceted by arm',
    'scaling.test.js: scaling: scatter, series = patient',
    'scaling.test.js: scaling: scatter, series = patient, colour = arm',
    'scaling.test.js: scaling: scatter, series = patient, faceted by arm',
    'scaling.test.js: scaling: line, categorical x with a level per patient'
  ]
};
